template = "https://github.com/giellalt/template-lang-und"
rev_id = 284
template_sha = "2037eca89479d8af6ddb6e31e662c34f302461e6"

[replacements]
__GLOTTOLOG_ID__ = "nort2641"
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
