template = "https://github.com/giellalt/template-lang-und"
rev_id = 320
template_sha = "67266bcec9c778bce3d70cc0a78e75bdec65cc66"

[replacements]
__GLOTTOLOG_ID__ = "nort2641"
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
